//! Deploy-time config wizard (`feature = "wizard"`, `dratchetd-config-
//! wizard` binary, `src/bin/config_wizard.rs`) — walks an operator through
//! `dratchetd`'s actual configurable surface and emits a Helm values
//! *override* file for `chart/dratchet-server`, meant to be applied with
//! `helm install -f <file>` on top of the chart's own defaults.
//!
//! Deliberately **not** a rewrite of `chart/dratchet-server/values.yaml`:
//! this only renders the fields an operator actually answered, so every
//! safety comment and warning already in that file (the `replicaCount`
//! sharding warning, the TLS setup notes) stays exactly where it is and
//! still applies — no YAML-parsing/comment-preservation problem to solve,
//! and no risk of this module's output silently drifting from the chart's
//! real schema (guarded by `every_key_path_the_wizard_writes_exists_in_the_real_chart_schema`
//! below).
//!
//! `dratchetd` itself is deliberately *not* runtime-configurable beyond its
//! bind address (`server/README.md`'s Configuration section) — this wizard
//! only ever produces a *deploy-time* file; nothing here talks to a running
//! server or changes its behavior without a restart.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WizardAnswers {
    pub service_port: u16,
    pub log_level: String,
    pub image_repository: String,
    pub image_tag: String,
    pub replica_count: u32,
    pub resource_tier: ResourceTier,
    pub ingress: Option<IngressAnswers>,
    pub pod_disruption_budget: bool,
}

impl Default for WizardAnswers {
    fn default() -> Self {
        WizardAnswers {
            service_port: 8787,
            log_level: "info".to_string(),
            image_repository: "dratchet-server".to_string(),
            image_tag: "latest".to_string(),
            replica_count: 1,
            resource_tier: ResourceTier::Dev,
            ingress: None,
            pod_disruption_budget: false,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ResourceTier {
    /// The chart's own defaults (`50m`/`32Mi` request, `500m`/`256Mi`
    /// limit) already are this tier, so it overrides nothing.
    Dev,
    SmallProd,
    /// Sized per-replica — the chart's `replicaCount` multiplies it.
    Ha,
    Custom {
        requests_cpu: String,
        requests_memory: String,
        limits_cpu: String,
        limits_memory: String,
    },
}

impl ResourceTier {
    /// `(requests.cpu, requests.memory, limits.cpu, limits.memory)`, or
    /// `None` for `Dev` (nothing to override).
    fn values(&self) -> Option<(String, String, String, String)> {
        match self {
            ResourceTier::Dev => None,
            ResourceTier::SmallProd => {
                Some(("250m".into(), "128Mi".into(), "1".into(), "1Gi".into()))
            }
            ResourceTier::Ha => Some(("250m".into(), "256Mi".into(), "2".into(), "512Mi".into())),
            ResourceTier::Custom {
                requests_cpu,
                requests_memory,
                limits_cpu,
                limits_memory,
            } => Some((
                requests_cpu.clone(),
                requests_memory.clone(),
                limits_cpu.clone(),
                limits_memory.clone(),
            )),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct IngressAnswers {
    pub host: String,
    pub tls: TlsMode,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum TlsMode {
    /// Plain `ws://` externally — the rendered file still sets
    /// `ingress.enabled: true`, the chart's own NOTES.txt calls out the
    /// lack of TLS explicitly (never a silent gap).
    None,
    CertManager {
        cluster_issuer: String,
        secret_name: String,
    },
    ExistingSecret {
        secret_name: String,
    },
}

/// Render `answers` as a Helm values override file for
/// `chart/dratchet-server`. A pure function — no I/O, no terminal — so it's
/// fully unit-testable independent of `collect_answers_interactive` below.
pub fn render_values_override(answers: &WizardAnswers) -> String {
    let mut out = String::new();

    out.push_str("# Generated by dratchetd-config-wizard.\n");
    out.push_str("# Apply on top of chart/dratchet-server's own defaults with:\n");
    out.push_str("#   helm upgrade --install dratchet chart/dratchet-server -f <this file>\n\n");

    out.push_str("image:\n");
    out.push_str(&format!("  repository: {}\n", answers.image_repository));
    out.push_str(&format!("  tag: \"{}\"\n\n", answers.image_tag));

    out.push_str(&format!("replicaCount: {}\n\n", answers.replica_count));

    out.push_str("service:\n");
    out.push_str(&format!("  port: {}\n\n", answers.service_port));

    out.push_str("config:\n");
    out.push_str(&format!("  logLevel: \"{}\"\n\n", answers.log_level));

    if let Some((requests_cpu, requests_memory, limits_cpu, limits_memory)) =
        answers.resource_tier.values()
    {
        out.push_str("resources:\n");
        out.push_str("  requests:\n");
        out.push_str(&format!("    cpu: {requests_cpu}\n"));
        out.push_str(&format!("    memory: {requests_memory}\n"));
        out.push_str("  limits:\n");
        out.push_str(&format!("    cpu: {limits_cpu}\n"));
        out.push_str(&format!("    memory: {limits_memory}\n\n"));
    }

    if let Some(ingress) = &answers.ingress {
        out.push_str("ingress:\n");
        out.push_str("  enabled: true\n");
        if let TlsMode::CertManager { cluster_issuer, .. } = &ingress.tls {
            out.push_str("  annotations:\n");
            out.push_str(&format!(
                "    cert-manager.io/cluster-issuer: {cluster_issuer}\n"
            ));
        }
        out.push_str("  hosts:\n");
        out.push_str(&format!("    - host: {}\n", ingress.host));
        out.push_str("      paths:\n");
        out.push_str("        - path: /\n");
        out.push_str("          pathType: Prefix\n");
        match &ingress.tls {
            TlsMode::None => {}
            TlsMode::CertManager { secret_name, .. } | TlsMode::ExistingSecret { secret_name } => {
                out.push_str("  tls:\n");
                out.push_str(&format!("    - hosts: [\"{}\"]\n", ingress.host));
                out.push_str(&format!("      secretName: {secret_name}\n"));
            }
        }
        out.push('\n');
    }

    if answers.pod_disruption_budget {
        out.push_str("podDisruptionBudget:\n");
        out.push_str("  enabled: true\n\n");
    }

    out
}

/// The only function in this module that touches a terminal — separated
/// from [`render_values_override`] so the rendering logic stays testable
/// without a PTY, and so `dratchetd-config-wizard --non-interactive
/// <answers.json>` can skip straight to rendering (used by CI, which has
/// no PTY to drive real prompts with).
pub fn collect_answers_interactive() -> WizardAnswers {
    use dialoguer::theme::ColorfulTheme;
    use dialoguer::{Confirm, Input, Select};

    let theme = ColorfulTheme::default();

    let service_port: u16 = Input::with_theme(&theme)
        .with_prompt("Service port (dratchetd's WebSocket/HTTP listener)")
        .default(8787)
        .interact_text()
        .expect("terminal input");

    let log_level: String = Input::with_theme(&theme)
        .with_prompt("Log level (RUST_LOG-style filter)")
        .default("info".to_string())
        .interact_text()
        .expect("terminal input");

    let image_repository: String = Input::with_theme(&theme)
        .with_prompt("Container image repository")
        .default("dratchet-server".to_string())
        .interact_text()
        .expect("terminal input");

    let image_tag: String = Input::with_theme(&theme)
        .with_prompt("Container image tag")
        .default("latest".to_string())
        .interact_text()
        .expect("terminal input");

    let mut replica_count: u32 = Input::with_theme(&theme)
        .with_prompt("Replica count")
        .default(1u32)
        .interact_text()
        .expect("terminal input");

    if replica_count > 1 {
        let confirmed = Confirm::with_theme(&theme)
            .with_prompt(
                "dratchetd holds all state in-memory, per pod, with nothing shared \
                 between replicas (chart/dratchet-server/values.yaml's replicaCount \
                 comment) — more than one pod gives you N independent, inconsistent \
                 copies unless you've separately solved sticky routing per identity \
                 fingerprint at your ingress/LB. Continue with more than one replica?",
            )
            .default(false)
            .interact()
            .expect("terminal input");
        if !confirmed {
            replica_count = 1;
        }
    }

    let tier_options = [
        "Dev/test (chart defaults)",
        "Small production",
        "HA (sized per replica)",
        "Custom",
    ];
    let tier_choice = Select::with_theme(&theme)
        .with_prompt("Resource tier")
        .items(&tier_options)
        .default(0)
        .interact()
        .expect("terminal input");
    let resource_tier = match tier_choice {
        0 => ResourceTier::Dev,
        1 => ResourceTier::SmallProd,
        2 => ResourceTier::Ha,
        _ => ResourceTier::Custom {
            requests_cpu: Input::with_theme(&theme)
                .with_prompt("resources.requests.cpu")
                .interact_text()
                .expect("terminal input"),
            requests_memory: Input::with_theme(&theme)
                .with_prompt("resources.requests.memory")
                .interact_text()
                .expect("terminal input"),
            limits_cpu: Input::with_theme(&theme)
                .with_prompt("resources.limits.cpu")
                .interact_text()
                .expect("terminal input"),
            limits_memory: Input::with_theme(&theme)
                .with_prompt("resources.limits.memory")
                .interact_text()
                .expect("terminal input"),
        },
    };

    let want_ingress = Confirm::with_theme(&theme)
        .with_prompt("Configure an Ingress (recommended for wss:// / TLS)?")
        .default(false)
        .interact()
        .expect("terminal input");

    let ingress = if want_ingress {
        let host: String = Input::with_theme(&theme)
            .with_prompt("Ingress hostname")
            .default("dratchet.example.com".to_string())
            .interact_text()
            .expect("terminal input");

        let tls_options = [
            "None (plain ws:// externally)",
            "cert-manager",
            "Existing TLS Secret",
        ];
        let tls_choice = Select::with_theme(&theme)
            .with_prompt("TLS")
            .items(&tls_options)
            .default(1)
            .interact()
            .expect("terminal input");
        let tls = match tls_choice {
            0 => TlsMode::None,
            1 => TlsMode::CertManager {
                cluster_issuer: Input::with_theme(&theme)
                    .with_prompt("cert-manager ClusterIssuer name")
                    .default("letsencrypt-prod".to_string())
                    .interact_text()
                    .expect("terminal input"),
                secret_name: Input::with_theme(&theme)
                    .with_prompt("TLS Secret name (cert-manager creates/renews it)")
                    .default("dratchet-tls".to_string())
                    .interact_text()
                    .expect("terminal input"),
            },
            _ => TlsMode::ExistingSecret {
                secret_name: Input::with_theme(&theme)
                    .with_prompt("Existing TLS Secret name")
                    .interact_text()
                    .expect("terminal input"),
            },
        };
        Some(IngressAnswers { host, tls })
    } else {
        None
    };

    let pod_disruption_budget = replica_count > 1
        && Confirm::with_theme(&theme)
            .with_prompt("Enable a PodDisruptionBudget (minAvailable: 1)?")
            .default(true)
            .interact()
            .expect("terminal input");

    WizardAnswers {
        service_port,
        log_level,
        image_repository,
        image_tag,
        replica_count,
        resource_tier,
        ingress,
        pod_disruption_budget,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_answers_render_the_minimal_expected_override() {
        let rendered = render_values_override(&WizardAnswers::default());
        assert!(rendered.contains("replicaCount: 1"));
        assert!(rendered.contains("port: 8787"));
        assert!(rendered.contains("logLevel: \"info\""));
        // Dev tier overrides nothing — the chart's own defaults already are
        // this tier.
        assert!(!rendered.contains("resources:"));
        assert!(!rendered.contains("ingress:"));
        assert!(!rendered.contains("podDisruptionBudget:"));
    }

    #[test]
    fn scaling_past_one_replica_renders_the_chosen_count_and_gates_the_pdb_block_on_its_own_flag() {
        let mut answers = WizardAnswers {
            replica_count: 3,
            ..WizardAnswers::default()
        };
        let without_pdb = render_values_override(&answers);
        assert!(without_pdb.contains("replicaCount: 3"));
        assert!(!without_pdb.contains("podDisruptionBudget:"));

        answers.pod_disruption_budget = true;
        let with_pdb = render_values_override(&answers);
        assert!(with_pdb.contains("podDisruptionBudget:"));
        assert!(with_pdb.contains("enabled: true"));
    }

    #[test]
    fn cert_manager_ingress_renders_the_issuer_annotation_and_a_tls_block() {
        let answers = WizardAnswers {
            ingress: Some(IngressAnswers {
                host: "dratchet.example.com".into(),
                tls: TlsMode::CertManager {
                    cluster_issuer: "letsencrypt-prod".into(),
                    secret_name: "dratchet-tls".into(),
                },
            }),
            ..WizardAnswers::default()
        };
        let rendered = render_values_override(&answers);
        assert!(rendered.contains("cert-manager.io/cluster-issuer: letsencrypt-prod"));
        assert!(rendered.contains("secretName: dratchet-tls"));
        assert!(rendered.contains("host: dratchet.example.com"));
    }

    #[test]
    fn existing_secret_ingress_renders_the_secret_name_with_no_cert_manager_annotation() {
        let answers = WizardAnswers {
            ingress: Some(IngressAnswers {
                host: "dratchet.example.com".into(),
                tls: TlsMode::ExistingSecret {
                    secret_name: "my-existing-tls".into(),
                },
            }),
            ..WizardAnswers::default()
        };
        let rendered = render_values_override(&answers);
        assert!(!rendered.contains("cert-manager.io/cluster-issuer"));
        assert!(rendered.contains("secretName: my-existing-tls"));
    }

    #[test]
    fn no_tls_ingress_still_enables_ingress_with_no_tls_block() {
        let answers = WizardAnswers {
            ingress: Some(IngressAnswers {
                host: "dratchet.example.com".into(),
                tls: TlsMode::None,
            }),
            ..WizardAnswers::default()
        };
        let rendered = render_values_override(&answers);
        assert!(rendered.contains("enabled: true"));
        assert!(!rendered.contains("tls:"));
    }

    #[test]
    fn custom_resource_tier_renders_the_exact_typed_values() {
        let answers = WizardAnswers {
            resource_tier: ResourceTier::Custom {
                requests_cpu: "1".into(),
                requests_memory: "2Gi".into(),
                limits_cpu: "4".into(),
                limits_memory: "8Gi".into(),
            },
            ..WizardAnswers::default()
        };
        let rendered = render_values_override(&answers);
        assert!(rendered.contains("cpu: 1\n"));
        assert!(rendered.contains("memory: 2Gi\n"));
        assert!(rendered.contains("cpu: 4\n"));
        assert!(rendered.contains("memory: 8Gi\n"));
    }

    /// Schema-drift guard: every dotted key path this module ever writes is
    /// confirmed present as a real key somewhere in the chart's own
    /// `values.yaml`, so the wizard can't silently diverge from the
    /// chart's actual schema as the chart evolves.
    #[test]
    fn every_key_path_the_wizard_writes_exists_in_the_real_chart_schema() {
        let chart_values = include_str!("../../chart/dratchet-server/values.yaml");
        let keys = [
            "image:",
            "repository:",
            "tag:",
            "replicaCount:",
            "service:",
            "port:",
            "config:",
            "logLevel:",
            "resources:",
            "requests:",
            "limits:",
            "cpu:",
            "memory:",
            "ingress:",
            "enabled:",
            "annotations:",
            "hosts:",
            "host:",
            "paths:",
            "path:",
            "pathType:",
            "tls:",
            "secretName:",
            "podDisruptionBudget:",
        ];
        for key in keys {
            assert!(
                chart_values.contains(key),
                "wizard emits `{key}` but it's not a key anywhere in \
                 chart/dratchet-server/values.yaml"
            );
        }
    }
}
