//! Phase 1.6.3: the two mandatory-verification paths from
//! `docs/ARCHITECTURE.md` §6.3 (in-person QR) and §6.4 (remote pairing
//! code) — data layer only. Both paths verify a session that already
//! exists (directory-based X3DH already ran, per §6.5); neither carries
//! handshake material or a routing id (that's §6.3a's QR-carries-
//! everything extension, v2, not this). SAS (§6.3a) is out of v1 scope,
//! matching the confirmed decision for this phase.
//!
//! **Out of scope, deliberately**: live camera QR *scanning* (needs a
//! webview `getUserMedia` call, i.e. an actual GUI this sandbox can't
//! build or verify) and any real Tauri shell. QR *generation* (the data
//! format and rendering a real, scannable PNG) is in scope and fully
//! testable headlessly.

use std::io::Cursor;

use rand_core::{OsRng, RngCore};
use serde::{Deserialize, Serialize};

use crate::error::{Error, Result};

/// How long a rendered QR code stays valid before it's considered stale —
/// long enough for an unhurried in-person exchange, short enough that a
/// screenshotted old code is visibly rejectable (§6.3: "a short random
/// nonce so a stale photographed code is visibly different from a fresh
/// one").
pub const QR_VALIDITY_SECS: u64 = 300;

/// §6.3's QR payload: `username#NNNN` + the SHA-256 fingerprint of the
/// current identity key + a nonce and timestamp, so a stale photographed
/// code can be told apart from a fresh one.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct QrVerificationPayload {
    pub username: String,
    pub discriminator: u16,
    #[serde(with = "serde_bytes")]
    pub fingerprint: Vec<u8>,
    #[serde(with = "serde_bytes")]
    pub nonce: Vec<u8>,
    pub generated_at: u64,
}

impl QrVerificationPayload {
    pub fn new(username: String, discriminator: u16, fingerprint: Vec<u8>, now: u64) -> Self {
        let mut nonce = vec![0u8; 16];
        OsRng.fill_bytes(&mut nonce);
        QrVerificationPayload {
            username,
            discriminator,
            fingerprint,
            nonce,
            generated_at: now,
        }
    }

    pub fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        ciborium::into_writer(self, &mut bytes)
            .expect("CBOR encoding of a well-formed struct cannot fail");
        bytes
    }

    pub fn decode(bytes: &[u8]) -> Result<Self> {
        ciborium::from_reader(bytes)
            .map_err(|_| Error::MalformedRecord("not a valid QrVerificationPayload"))
    }

    /// True once `QR_VALIDITY_SECS` has passed since this code was
    /// generated — a scanner must refuse a stale code rather than verify
    /// against it (§6.3: "mismatch is a hard stop," and a stale code that
    /// might no longer reflect the device's *current* identity key is the
    /// same kind of risk).
    pub fn is_stale(&self, now: u64) -> bool {
        now.saturating_sub(self.generated_at) > QR_VALIDITY_SECS
    }

    /// Render this payload as a real, scannable QR code PNG.
    pub fn render_png(&self) -> Result<Vec<u8>> {
        render_qr_png(&self.encode())
    }
}

fn render_qr_png(data: &[u8]) -> Result<Vec<u8>> {
    let code = qrcode::QrCode::new(data)
        .map_err(|_| Error::MalformedRecord("payload too large to encode as a QR code"))?;
    let image = code.render::<image::Luma<u8>>().build();
    let mut png_bytes = Vec::new();
    image::DynamicImage::ImageLuma8(image)
        .write_to(&mut Cursor::new(&mut png_bytes), image::ImageFormat::Png)
        .map_err(|_| Error::MalformedRecord("failed to encode QR code as PNG"))?;
    Ok(png_bytes)
}

/// §6.4's remote pairing code TTL: ~10 minutes.
pub const PAIRING_CODE_TTL_SECS: u64 = 600;
/// §6.4: "attempts are rate-limited — a 6-digit space is brute-forceable
/// without that limit." A fresh code (via `PairingCode::generate`) is
/// required after this many wrong attempts, exactly as the text says.
pub const PAIRING_CODE_MAX_ATTEMPTS: u32 = 5;

/// §6.4's remote pairing code: generated by the recipient, read to the
/// initiator over a separately-trusted channel, and bound to *this*
/// handshake's key material (`bound_to` — typically the conversation id or
/// the initiator's identity fingerprint) so it can't be replayed against a
/// different session.
#[derive(Clone, Serialize, Deserialize)]
pub struct PairingCode {
    pub code: String,
    pub generated_at: u64,
    #[serde(with = "serde_bytes")]
    pub bound_to: Vec<u8>,
    pub attempts: u32,
}

/// Hand-written, not `#[derive(Debug)]`: `code` authenticates a pairing
/// attempt the same way a one-time passcode does — printing it via `{:?}`
/// would put a live, still-usable secret in a log file.
impl std::fmt::Debug for PairingCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PairingCode")
            .field("code", &"<redacted>")
            .field("generated_at", &self.generated_at)
            .field("bound_to", &crate::db::hex(&self.bound_to))
            .field("attempts", &self.attempts)
            .finish()
    }
}

impl PairingCode {
    /// A fresh 6-digit code. Per §6.4 step 2: "generating a new one
    /// invalidates the previous code" — the caller achieves that simply by
    /// discarding/overwriting whatever `PairingCode` it was holding, since
    /// this type carries no identity of its own beyond `bound_to`.
    pub fn generate(bound_to: Vec<u8>, now: u64) -> Self {
        let code = format!("{:06}", OsRng.next_u32() % 1_000_000);
        PairingCode {
            code,
            generated_at: now,
            bound_to,
            attempts: 0,
        }
    }

    pub fn is_expired(&self, now: u64) -> bool {
        now.saturating_sub(self.generated_at) > PAIRING_CODE_TTL_SECS
    }

    fn attempts_exhausted(&self) -> bool {
        self.attempts >= PAIRING_CODE_MAX_ATTEMPTS
    }

    /// Check `attempted_code` against this pairing code, bound to
    /// `attempted_bound_to` (the session actually being verified) at time
    /// `now`. Every call — match or not — counts as an attempt, so this
    /// takes `&mut self`: the caller is expected to persist the updated
    /// attempt count (or the whole struct) regardless of outcome, the same
    /// way a wrong guess still costs an attempt against a real budget.
    pub fn verify(&mut self, attempted_code: &str, attempted_bound_to: &[u8], now: u64) -> bool {
        if self.is_expired(now) || self.attempts_exhausted() {
            return false;
        }
        self.attempts += 1;
        // Constant-time-ish by not short-circuiting on the first
        // mismatched field before counting the attempt — the attempt
        // count above is charged regardless of which check below fails.
        self.code == attempted_code && self.bound_to == attempted_bound_to
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pairing_codes_debug_output_never_contains_the_live_code() {
        let code = PairingCode::generate(vec![1u8; 16], 1_000);
        let debug_output = format!("{code:?}");
        assert!(
            !debug_output.contains(&code.code),
            "the live pairing code must never appear in Debug output: {debug_output}"
        );
    }

    #[test]
    fn qr_payload_round_trips_through_encode_and_decode() {
        let payload = QrVerificationPayload::new("alice".into(), 4821, vec![9u8; 32], 1_000);
        let decoded = QrVerificationPayload::decode(&payload.encode()).unwrap();
        assert_eq!(decoded, payload);
    }

    #[test]
    fn qr_payload_is_fresh_right_after_generation_and_stale_after_the_validity_window() {
        let payload = QrVerificationPayload::new("alice".into(), 4821, vec![9u8; 32], 1_000);
        assert!(!payload.is_stale(1_000));
        assert!(!payload.is_stale(1_000 + QR_VALIDITY_SECS));
        assert!(payload.is_stale(1_000 + QR_VALIDITY_SECS + 1));
    }

    #[test]
    fn two_renders_of_the_same_identity_have_different_nonces() {
        let a = QrVerificationPayload::new("alice".into(), 4821, vec![9u8; 32], 1_000);
        let b = QrVerificationPayload::new("alice".into(), 4821, vec![9u8; 32], 1_000);
        assert_ne!(
            a.nonce, b.nonce,
            "a stale photographed code must be visibly different from a fresh one"
        );
    }

    #[test]
    fn rendered_qr_png_is_a_real_decodable_qr_code() {
        let payload = QrVerificationPayload::new("alice".into(), 4821, vec![9u8; 32], 1_000);
        let png_bytes = payload.render_png().unwrap();

        // Not a mock: decode the actual PNG bytes with an independent
        // (pure-Rust) QR decoder and confirm we get the same payload back.
        let image = image::load_from_memory(&png_bytes).unwrap().to_luma8();
        let mut prepared = rqrr::PreparedImage::prepare(image);
        let grids = prepared.detect_grids();
        assert_eq!(grids.len(), 1, "the PNG should contain exactly one QR code");
        // `decode()` forces the result through UTF-8 (`String`), which
        // our CBOR bytes generally aren't — `decode_to` writes the raw
        // bytes the QR code actually carried instead.
        let mut raw = Vec::new();
        grids[0].decode_to(&mut raw).unwrap();
        let decoded = QrVerificationPayload::decode(&raw).unwrap();
        assert_eq!(decoded, payload);
    }

    #[test]
    fn pairing_code_verifies_the_correct_code_bound_to_the_right_session() {
        let bound_to = vec![1u8; 16];
        let mut code = PairingCode::generate(bound_to.clone(), 1_000);
        let correct = code.code.clone();
        assert!(code.verify(&correct, &bound_to, 1_000));
    }

    #[test]
    fn pairing_code_rejects_the_wrong_code() {
        let bound_to = vec![1u8; 16];
        let mut code = PairingCode::generate(bound_to.clone(), 1_000);
        let wrong = if code.code == "000000" {
            "111111"
        } else {
            "000000"
        };
        assert!(!code.verify(wrong, &bound_to, 1_000));
    }

    /// §6.4: a pairing code authenticates the account, not a specific
    /// session — binding to the wrong session must fail even with the
    /// right digits, so a code can't be replayed against a different
    /// handshake than the one it was actually generated for.
    #[test]
    fn pairing_code_rejects_the_right_code_bound_to_the_wrong_session() {
        let mut code = PairingCode::generate(vec![1u8; 16], 1_000);
        let correct = code.code.clone();
        assert!(!code.verify(&correct, &[2u8; 16], 1_000));
    }

    #[test]
    fn pairing_code_expires_after_its_ttl() {
        let bound_to = vec![1u8; 16];
        let mut code = PairingCode::generate(bound_to.clone(), 1_000);
        let correct = code.code.clone();
        assert!(!code.verify(&correct, &bound_to, 1_000 + PAIRING_CODE_TTL_SECS + 1));
    }

    #[test]
    fn pairing_code_attempts_are_rate_limited() {
        let bound_to = vec![1u8; 16];
        let mut code = PairingCode::generate(bound_to.clone(), 1_000);
        let correct = code.code.clone();

        for _ in 0..PAIRING_CODE_MAX_ATTEMPTS {
            assert!(!code.verify("000000", &bound_to, 1_000));
        }
        // Attempts exhausted — even the *correct* code is now refused
        // until a fresh one is generated, per §6.4's "a fresh code is
        // required for another attempt."
        assert!(
            !code.verify(&correct, &bound_to, 1_000),
            "the correct code must still be refused once attempts are exhausted"
        );
    }
}
